name: trimly-dev

services:
  trimly-backend:
    build: ./backend
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
  trimly-frontend:
    build: ./frontend
    depends_on:
      - trimly-backend
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/localhost.crt:/root/ssl/localhost.crt
      - ./nginx/certs/localhost.key:/root/ssl/localhost.key
    depends_on:
      - trimly-backend
      - trimly-frontend
