name: trimly

services:
  trimly-backend:
    build: ./backend
    env_file:
      - .env
  trimly-frontend:
    build: ./frontend
    depends_on:
      - trimly-backend
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - trimly-backend
      - trimly-frontend
