name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build Deployment Package
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3

      - name: Installing all dependencies
        run: npm run devinstall

      - name: Build .env file
        run: echo "${{ secrets.ENV_CONFIG }}" >> .env

      - name: Build TLS Certs
        run: |
          mkdir -p "certbot/conf/live/${{ secrets.DOMAIN }}"
          echo "${{ secrets.SSL_CERT }}" >> "certbot/conf/live/${{ secrets.DOMAIN }}/fullchain.pem"
          echo "${{ secrets.SSL_CERT_KEY }}" >> "certbot/conf/live/${{ secrets.DOMAIN }}/privkey.pem"

      - name: Building Frontend and Backend
        run: |
          export CI=false
          npm run build

      - name: Removing development dependencies
        run: |
          rm -rf node_modules
          cd frontend && rm -rf node_modules
          cd ..
          cd backend && rm -rf node_modules
          cd ..

      - name: Creating custom nginx config
        run: |
          mkdir -p nginx
          touch nginx/default.conf
          echo '${{ secrets.NGINX_CONFIG }}' >> nginx/default.conf

      - name: Creating Deployment Zip
        run: |
          zip -r deploy.zip .

      - name: Creating Version Label
        shell: bash
        run: echo "##[set-output name=timestamp;]$(env TZ=Asia/Singapore date '+%Y%m%d%H%M%S')"
        id: get_timestamp

      - name: Deploying to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.get_timestamp.outputs.timestamp }}
          deployment_package: deploy.zip
          region: ap-southeast-1
